In [11]:
%matplotlib inline
import warnings
import itertools
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta
from datetime import date
import statsmodels.api as sm
from statsmodels.tsa.arima_model import ARIMA
import matplotlib.pyplot as plt
from datetime import date
from dateutil.relativedelta import relativedelta
import sys
from IPython.core.debugger import set_trace


###Load Data

In [12]:
m3_year = pd.read_excel('../data/M3C.xls',0)
m3_quar = pd.read_excel('../data/M3C.xls',1)
m3_mont = pd.read_excel('../data/M3C.xls',2)
m3_mont = m3_mont[m3_mont['Starting Year'] != 0]

len(m3_year)+len(m3_quar)+len(m3_mont)
print(len(m3_quar))

756


In [13]:
def convert_to_date(init_year, init_quarter_month, x, quarter_multiplier):
    year = int(init_year)
    new_date = date(year,1,1) + relativedelta(months=+quarter_multiplier*init_quarter_month) + relativedelta(months=+quarter_multiplier*x)
    return new_date

In [59]:
def series_to_dataframes(values, dates):
    size = int(len(values) * 0.3)
    train, test = values[0:size], values[size:len(values)]
    train_dates, test_dates = dates[0:size], dates[size:len(values)]
    
    train_df = pd.DataFrame(data= train, index = train_dates, columns = ["value"])
    train_df = train_df.convert_objects(convert_numeric=True)
    train_df = train_df[np.isfinite(train_df['value'])]
    
    test_df = pd.DataFrame(data= test, index = test_dates, columns = ["value"])
    test_df = test_df.convert_objects(convert_numeric=True)
    test_df = test_df[np.isfinite(test_df['value'])]
    
    print(test_df.values)

    return train_df, test_df

###Transform to right format as a list of pandas dataframes each containing a timeseries (

In [60]:
train_year_dfs = []
test_year_dfs = []

for i in range (0,len(m3_year)):
    series = m3_year.iloc[i,6:53]
    init_year = m3_year.iloc[i,4]
    dates_list = [date(int(init_year+x),1,1) for x in range(0,len(series))] 
    
    train_df, test_df = series_to_dataframes(series.values, dates_list)
    train_year_dfs.append(train_df)
    test_year_dfs.append(test_df)    
             
train_quar_dfs = []        
test_quar_dfs = []
for i in range (0,len(m3_quar)):
    series = m3_quar.iloc[i,6:77]
    init_year = m3_quar.iloc[i,4]
    init_quar = m3_quar.iloc[i,5]
    dates_list =  [convert_to_date(init_year,init_quar,x, 3) for x in range(0,len(series))] 
    
    train_df, test_df = series_to_dataframes(series.values, dates_list)
    train_quar_dfs.append(train_df)
    test_quar_dfs.append(test_df)
    
train_mont_dfs = []
test_mont_dfs = []
for i in range (0,len(m3_mont)):
    series = m3_mont.iloc[i,6:149]
    init_year = m3_mont.iloc[i,4]
    init_month = m3_mont.iloc[i,5]
    dates_list =  [convert_to_date(init_year,init_month,x, 1) for x in range(0,len(series))] 
    
    train_df, test_df = series_to_dataframes(series.values, dates_list)
    train_mont_dfs.append(train_df)
    test_mont_dfs.append(test_df)

[[5379.75]
 [6158.68]
 [6876.58]
 [7851.91]
 [8407.84]
 [9156.01]]
[[4793.2]
 [5602. ]
 [5065. ]
 [5056. ]
 [5067.2]
 [5209.6]]
[[3070.2]
 [3601.6]
 [3407.4]
 [3500.6]
 [3437.8]
 [3007. ]]
[[4656.  ]
 [5228.52]
 [5656.72]
 [5077.02]
 [5403.4 ]
 [5009.52]]
[[5250.9]
 [4899.2]
 [4317.9]
 [4007.9]
 [4323.4]
 [4819.4]]
[[4338.03]
 [4185.92]
 [3950.49]
 [3715.59]
 [3958.3 ]
 [4140.39]]
[[5163.21]
 [5089.94]
 [4786.4 ]
 [4926.47]
 [5068.83]
 [5318.19]]
[[8809.8 ]
 [8953.5 ]
 [7991.01]
 [7294.08]
 [7163.37]
 [7478.31]]
[[6277.6 ]
 [7446.28]
 [6741.69]
 [6600.69]
 [7850.17]
 [8485.26]]
[[10042.9]
 [10173. ]
 [ 8751. ]
 [ 3472. ]
 [ 3187. ]
 [ 3058. ]]
[[5388.4]
 [5766.2]
 [5937.9]
 [5627.4]
 [5982.7]
 [5931.6]]
[[ 5949.5]
 [ 6616.5]
 [ 7247. ]
 [ 8205. ]
 [10158.5]
 [12495.5]]
[[6271. ]
 [6901.8]
 [6479.2]
 [6452.3]
 [6271.6]
 [6405.2]]
[[4010.8]
 [4120.8]
 [4084.2]
 [4330.2]
 [4552.4]
 [4724. ]]
[[5995. ]
 [6510.5]
 [6670. ]
 [6941.5]
 [7010. ]
 [7539.5]]
[[6658.3]
 [7101.4]
 [7375.8]
 [5748.

/home/cartest/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  import sys
/home/cartest/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  # This is added back by InteractiveShellApp.init_path()



[[3676.83]
 [4721.37]
 [5243.28]
 [6276.36]
 [7026.27]
 [8885.16]]
[[12523.5]
 [12166. ]
 [12881.5]
 [13480.5]
 [ 7086.5]
 [ 7598. ]]
[[4227.]
 [4481.]
 [4395.]
 [4602.]
 [4829.]
 [4841.]]
[[6747.02]
 [6775.18]
 [7079.44]
 [7873.68]
 [8304.85]
 [8966.21]]
[[ 7928.83]
 [ 7751.34]
 [ 8468.2 ]
 [ 9231.5 ]
 [ 9811.36]
 [11374.3 ]]
[[5025. ]
 [5062.6]
 [4878.6]
 [5099.6]
 [5050.8]
 [5505.4]]
[[4421.52]
 [4417.08]
 [3819.84]
 [3816.98]
 [3472.72]
 [4063.7 ]]
[[8061.94]
 [8551.94]
 [9303.02]
 [9592.14]
 [9611.4 ]
 [9505.  ]]
[[3070.2]
 [3601.6]
 [3407.4]
 [3500.6]
 [3437.8]
 [3007. ]]
[[ 3274.64]
 [ 3970.12]
 [ 5589.92]
 [ 9170.12]
 [ 8793.24]
 [10438.96]]
[[2509.23]
 [2835.65]
 [3193.03]
 [3756.92]
 [5400.23]
 [8299.04]]
[[ 8388.45]
 [ 8570.2 ]
 [ 8858.75]
 [ 9702.85]
 [11116.85]
 [12344.85]]
[[3464.8]
 [5180.4]
 [5090.2]
 [5245.8]
 [5217.4]
 [5713.4]]
[[2825.79]
 [2994.88]
 [3546.68]
 [5304.05]
 [6379.21]
 [7146.98]]
[[6462.07]
 [5119.36]
 [4035.35]
 [4815.54]
 [7010.89]
 [4328.  ]]
[[3889

 [12577.6]]
[[  656.85]
 [  695.2 ]
 [  760.9 ]
 [ 1019.25]
 [ 1377.35]
 [ 1546.8 ]
 [ 1537.45]
 [ 1414.85]
 [ 1235.25]
 [ 1228.95]
 [ 1346.1 ]
 [ 1483.05]
 [ 1775.8 ]
 [ 1751.9 ]
 [ 1985.1 ]
 [ 2265.45]
 [ 2858.  ]
 [ 3927.4 ]
 [ 4486.6 ]
 [ 4735.5 ]
 [ 5419.55]
 [ 5829.25]
 [ 6625.35]
 [ 7147.65]
 [ 7410.6 ]
 [ 7932.5 ]
 [ 9575.9 ]
 [12620.05]
 [12503.95]
 [12379.85]
 [11285.95]]
[[ 1057.2]
 [ 1095. ]
 [ 1165.8]
 [ 1369.6]
 [ 1571.1]
 [ 1795. ]
 [ 1634.3]
 [ 1429.8]
 [ 1288.2]
 [ 1399.7]
 [ 1532.2]
 [ 1669.5]
 [ 2088.9]
 [ 2216.8]
 [ 2414.1]
 [ 2611.9]
 [ 3022.3]
 [ 3037.7]
 [ 3719.9]
 [ 4659.1]
 [ 6320.1]
 [ 7443.5]
 [ 8562.6]
 [ 9233.4]
 [ 9500.9]
 [ 9243.9]
 [ 9239.4]
 [10779.7]
 [ 8201.7]
 [ 8482.7]
 [ 8124.1]]
[[ 774.45]
 [ 769.45]
 [ 866.05]
 [ 985.45]
 [1413.35]
 [2072.1 ]
 [2298.  ]
 [2165.45]
 [2380.1 ]
 [2373.4 ]
 [2829.35]
 [3127.65]
 [3101.6 ]
 [3224.7 ]
 [4393.25]
 [6599.8 ]
 [7319.1 ]
 [7377.55]
 [6543.4 ]]
[[ 1951. ]
 [ 1751.5]
 [ 1779. ]
 [ 2677. ]
 [ 2801. ]
 [ 4614.

[[4856. ]
 [5000. ]
 [5185. ]
 [5401.5]
 [5626.5]
 [5826. ]
 [5970. ]
 [6109. ]
 [6219.5]]
[[4836.5]
 [5000. ]
 [5169. ]
 [5387.5]
 [5670. ]
 [5913.5]
 [6146. ]
 [6282. ]
 [6390. ]]
[[4884.5]
 [5000. ]
 [5159. ]
 [5325.5]
 [5370.5]
 [5558. ]
 [5785.5]
 [5973.5]
 [6072. ]]
[[4552.5]
 [5000. ]
 [5284. ]
 [5231. ]
 [5089.5]
 [4944.5]
 [5086. ]
 [5070.5]
 [5144.5]]
[[4869. ]
 [5000. ]
 [5243. ]
 [5496. ]
 [5639.5]
 [5717. ]
 [5709. ]
 [5752.5]
 [5645. ]]
[[4929.5]
 [5000. ]
 [5141. ]
 [5247.5]
 [5360. ]
 [5479.5]
 [5561.5]
 [5643. ]
 [5626.5]]
[[4817.5]
 [5000. ]
 [5321. ]
 [5614. ]
 [6031. ]
 [6232.5]
 [6274. ]
 [6145. ]
 [6156. ]]
[[4791. ]
 [5000. ]
 [5180. ]
 [5325. ]
 [5517.5]
 [5623.5]
 [5688.5]
 [5654. ]
 [5782. ]]
[[4744. ]
 [5000. ]
 [5220. ]
 [5326. ]
 [5506.5]
 [5688. ]
 [5932. ]
 [6171. ]
 [6341.5]]
[[4904.5]
 [5000. ]
 [5083. ]
 [5103.5]
 [5120. ]
 [5160.5]
 [5222. ]
 [5359.5]
 [5472. ]]
[[4847. ]
 [5000. ]
 [5078.5]
 [5166. ]
 [5379. ]
 [5577. ]
 [5741.5]
 [5849. ]
 [5944.5]]

[[1201.53]
 [1224.16]
 [1244.85]
 [1265.13]
 [1280.58]
 [1298.74]
 [1320.28]
 [1343.35]
 [1370.85]
 [1402.16]
 [1441.26]
 [1470.96]
 [1501.2 ]
 [1531.53]
 [1561.5 ]
 [1590.33]
 [1619.11]
 [1648.63]
 [1677.45]
 [1701.3 ]
 [1722.71]
 [1742.15]
 [1763.83]
 [1782.06]
 [1805.87]
 [1827.53]
 [1846.13]
 [1863.93]
 [1880.49]
 [1897.65]
 [1915.76]
 [1935.5 ]]
[[ 6054.6]
 [ 6175.9]
 [ 6307.6]
 [ 6478.2]
 [ 6672.6]
 [ 6891.5]
 [ 7052.7]
 [ 7210.3]
 [ 7429.6]
 [ 7521.5]
 [ 7597.2]
 [ 7866.9]
 [ 8159.4]
 [ 8327.9]
 [ 8243.8]
 [ 8542.1]
 [ 8873.4]
 [ 9266.1]
 [ 9547.7]
 [ 9593.8]
 [ 9703. ]
 [ 9612.5]
 [ 9745. ]
 [10168.5]
 [10397.1]
 [10643.4]
 [10923.2]
 [11180.1]
 [11413.2]
 [11472.9]
 [11364.4]
 [11439. ]
 [11622.9]]
[[6700.]
 [5500.]
 [5700.]
 [5200.]
 [4500.]
 [3800.]
 [3800.]
 [3600.]
 [3500.]
 [4900.]
 [5900.]
 [5600.]
 [4900.]
 [5600.]
 [8500.]
 [7700.]
 [7100.]
 [6100.]
 [5800.]
 [7100.]
 [7600.]
 [9700.]
 [9600.]
 [7500.]
 [7200.]
 [7000.]
 [6200.]
 [5500.]
 [5300.]
 [5500.]
 [6700.]
 [74

[[4400.]
 [4400.]
 [4850.]
 [4700.]
 [4650.]
 [4550.]
 [4600.]
 [5150.]
 [5600.]
 [6100.]
 [6150.]
 [5800.]
 [5700.]
 [5450.]
 [5350.]
 [5200.]
 [5150.]
 [5350.]
 [5750.]
 [5950.]
 [6150.]
 [5800.]]
[[6440.]
 [6420.]
 [6500.]
 [6600.]
 [6340.]
 [6280.]
 [6080.]
 [6540.]
 [6920.]
 [7260.]
 [7200.]
 [6900.]
 [6800.]
 [6920.]
 [6840.]
 [6680.]
 [6440.]
 [6680.]
 [7120.]
 [7080.]
 [7120.]
 [6920.]]
[[4600.]
 [4850.]
 [4950.]
 [5050.]
 [5400.]
 [5550.]
 [5600.]
 [5650.]
 [5700.]
 [5600.]
 [5800.]
 [6000.]
 [6000.]
 [5950.]
 [6050.]
 [6150.]
 [6250.]
 [6350.]
 [6350.]
 [6500.]
 [6650.]
 [6500.]]
[[4540.]
 [4720.]
 [4460.]
 [4790.]
 [4910.]
 [5030.]
 [4840.]
 [4780.]
 [4750.]
 [4570.]
 [4660.]
 [4810.]
 [4810.]
 [5140.]
 [5220.]
 [5300.]
 [5170.]
 [5310.]
 [5400.]
 [5250.]
 [5270.]
 [5260.]]
[[6200.]
 [6500.]
 [6650.]
 [6800.]
 [7200.]
 [7300.]
 [7300.]
 [7550.]
 [7700.]
 [7700.]
 [8000.]
 [8100.]
 [8050.]
 [8100.]
 [8200.]
 [8250.]
 [8250.]
 [8500.]
 [8700.]
 [8850.]
 [9050.]
 [8800.]]
[[823

[[5405.]
 [4838.]
 [4598.]
 [4859.]
 [4858.]
 [4912.]
 [4765.]
 [4633.]
 [5111.]
 [5183.]
 [5456.]]
[[ 3579.]
 [ 6275.]
 [ 9590.]
 [ 4694.]
 [ 3794.]
 [ 3932.]
 [ 3623.]
 [ 5320.]
 [ 7666.]
 [12045.]
 [ 5263.]]
[[2863.]
 [5491.]
 [8725.]
 [4326.]
 [3604.]
 [3945.]
 [3864.]
 [5740.]
 [8659.]]
[[8403.]
 [8355.]
 [8232.]
 [8052.]
 [7876.]
 [7712.]
 [7546.]
 [7367.]
 [7025.]
 [6858.]
 [6752.]]
[[8519.]
 [9116.]
 [9102.]
 [8825.]
 [8565.]
 [8193.]
 [8347.]
 [7669.]
 [7110.]
 [6273.]
 [6046.]]
[[6382.]
 [6836.]
 [6633.]
 [6346.]
 [6611.]
 [6617.]
 [6039.]
 [6207.]
 [5778.]
 [5187.]
 [5033.]]
[[5764.]
 [6384.]
 [6834.]
 [6680.]
 [6344.]
 [5770.]
 [5936.]
 [5683.]
 [5540.]
 [5336.]
 [5107.]]
[[5092.]
 [5994.]
 [7284.]
 [7886.]
 [7612.]
 [7349.]
 [6636.]
 [6864.]
 [5685.]
 [4966.]
 [4655.]]
[[5700.]
 [5582.]
 [6836.]
 [8126.]
 [8559.]
 [7261.]
 [7225.]
 [6622.]
 [6091.]
 [4965.]
 [4937.]]
[[3300.]
 [3740.]
 [3500.]
 [5440.]
 [5360.]
 [7440.]
 [6640.]
 [8140.]
 [8800.]
 [6280.]
 [4800.]]
[[ 9346

[[4300.5]
 [5696.5]
 [4566. ]
 [4878.5]
 [4504. ]
 [4870.5]
 [4594. ]
 [4048. ]
 [3675.5]
 [3523.5]
 [3576. ]
 [2823.5]
 [2763. ]
 [5193.5]
 [2233. ]
 [2127. ]
 [2076.5]
 [2053. ]
 [2085. ]
 [1990. ]
 [2340. ]
 [2824. ]
 [3411. ]]
[[3049.5]
 [2587.3]
 [2780.5]
 [2520.2]
 [3299.8]
 [3936.2]
 [4397.8]
 [4138.1]
 [4216.2]
 [3976.8]
 [4643.4]
 [4097.5]
 [4993.5]
 [5759.1]
 [6729.8]
 [5068.9]
 [5609.4]
 [5271.9]
 [6439.2]
 [3821.7]
 [4832.8]
 [4476.4]
 [5525.1]]
[[5692.8]
 [5643.6]
 [5013.4]
 [5699.1]
 [5881.1]
 [5938.7]
 [5141.4]
 [5577.7]
 [6169.5]
 [6170.1]
 [5519.8]
 [6648.4]
 [7069.5]
 [7269.4]
 [6513.1]
 [7190.3]
 [7710.7]
 [7888.2]
 [7097. ]
 [8065.4]
 [8479.3]
 [8768. ]
 [7750.5]]
[[5802.04]
 [5802.44]
 [6213.58]
 [6900.  ]
 [7060.  ]
 [5710.  ]
 [6024.  ]
 [5780.  ]
 [6150.  ]
 [5920.  ]
 [6716.  ]
 [6020.  ]
 [6450.  ]
 [6066.  ]
 [6422.  ]
 [5782.  ]
 [5908.  ]
 [5848.  ]
 [6162.  ]
 [5582.  ]
 [5806.  ]
 [5796.  ]
 [6148.  ]]
[[2971. ]
 [4202.3]
 [3996.6]
 [3993.2]
 [3141.6]
 [4

[[1915.35]
 [1956.1 ]
 [2054.6 ]
 [2194.9 ]
 [2286.65]
 [2564.6 ]
 [3269.5 ]
 [3304.5 ]
 [3396.1 ]
 [3623.15]
 [3717.7 ]
 [3979.35]
 [4075.95]
 [4159.75]
 [4657.85]
 [4884.6 ]
 [5120.8 ]
 [5693.9 ]
 [6373.75]
 [6291.75]
 [6495.8 ]
 [6919.95]
 [7209.45]]
[[2527. ]
 [1599.5]
 [2980.5]
 [4735.5]
 [4332.5]
 [3379.5]
 [3492. ]
 [ 798.5]
 [1125. ]
 [1487.5]
 [3203.5]
 [ 503.5]
 [4134.5]
 [4239. ]
 [5652.5]
 [8232.5]
 [8819. ]
 [5248. ]
 [6138.5]
 [4779. ]
 [6008. ]
 [5348. ]
 [7859.5]]
[[ 2787.5]
 [ 3714.5]
 [ 3497.5]
 [ 2362.5]
 [ 2561. ]
 [ 4314. ]
 [ 5628.5]
 [ 1881. ]
 [ 3836.5]
 [ 5796. ]
 [ 3282. ]
 [ 2528. ]
 [ 3823.5]
 [ 4790.5]
 [ 3725. ]
 [ 2111. ]
 [ 3743. ]
 [ 7420.5]
 [ 3852.5]
 [ 2989. ]
 [ 7772.5]
 [11363. ]
 [ 6144.5]]
[[5898.25]
 [5925.75]
 [5564.  ]
 [5857.  ]
 [5868.75]
 [5535.75]
 [5200.75]
 [4612.  ]
 [2258.75]
 [5042.75]
 [4888.5 ]
 [5345.  ]
 [6038.25]
 [5051.75]
 [5319.  ]
 [6016.5 ]
 [5711.75]
 [5337.  ]
 [5162.  ]
 [5591.75]
 [4645.25]
 [5484.5 ]]
[[2740.4]
 [2825.8

[[6240. ]
 [6384. ]
 [6362.5]
 [6160. ]
 [6102. ]
 [5826.5]
 [5897.5]
 [5780. ]
 [6126.5]
 [6200.5]
 [6435.5]
 [6664. ]
 [6723.5]
 [7201. ]
 [7899.5]
 [8461. ]
 [8665.5]
 [8650. ]
 [8403.5]
 [8607. ]
 [8057.5]
 [8336. ]
 [7863. ]
 [7836.5]
 [7873.5]
 [8044.5]
 [8259. ]
 [8177. ]
 [8553.5]
 [8679.5]
 [8795. ]]
[[7850.7]
 [8031.7]
 [7940.1]
 [8011.4]
 [7933.2]
 [8048.4]
 [8099.7]
 [8176.8]
 [8333.4]
 [8437.3]
 [8558.5]
 [8583.6]
 [8665.4]
 [8794.8]
 [8933.6]
 [9031.5]
 [9161.5]
 [9212.6]
 [9183.2]
 [9304.1]
 [9313.2]
 [9216.8]
 [9234.5]
 [9206.9]
 [9151.4]
 [9133. ]
 [9212.3]
 [9291. ]
 [9298.5]
 [9381.8]
 [9403.9]]
[[3959. ]
 [4002.5]
 [4070. ]
 [4162.5]
 [4166.5]
 [4299. ]
 [4301. ]
 [4363.5]
 [4390. ]
 [4445.5]
 [4450. ]
 [4561. ]
 [4603.5]
 [4665. ]
 [4738.5]
 [4778.5]
 [4883.5]
 [4914. ]
 [5005. ]
 [5000.5]
 [5102. ]
 [5209. ]
 [5248.5]
 [5301. ]
 [5257. ]
 [5317. ]
 [5394. ]
 [5431.5]
 [5405. ]
 [5465. ]
 [5482.5]]
[[3550.5]
 [3673. ]
 [3785.5]
 [3892.5]
 [3931.5]
 [4084.5]
 [4195.

[[3344.]
 [3398.]
 [3488.]
 [3574.]
 [3658.]
 [3742.]
 [3828.]
 [3872.]
 [3958.]
 [4006.]
 [4106.]
 [4022.]
 [4164.]
 [4236.]
 [4296.]
 [4308.]
 [4278.]
 [4326.]
 [4456.]
 [4548.]
 [4494.]
 [4458.]
 [4316.]
 [4166.]
 [4134.]
 [4238.]
 [4272.]
 [4288.]
 [4378.]
 [4402.]
 [4502.]]
[[4655.]
 [5025.]
 [4500.]
 [4135.]
 [2770.]
 [2320.]
 [1855.]
 [3185.]
 [4180.]
 [4855.]
 [5090.]
 [5800.]
 [5760.]
 [5400.]
 [5560.]
 [4340.]
 [4705.]
 [4395.]
 [3955.]
 [4455.]
 [4885.]
 [2890.]
 [2920.]
 [3885.]
 [3910.]
 [3450.]
 [3910.]
 [5205.]
 [4880.]
 [4555.]
 [5905.]]
[[4606.]
 [3162.]
 [3594.]
 [3994.]
 [4508.]
 [3494.]
 [3030.]
 [3700.]
 [1982.]
 [2320.]
 [3410.]
 [3240.]
 [3036.]
 [3048.]
 [3128.]
 [3640.]
 [2970.]
 [2580.]
 [2976.]
 [3462.]
 [3654.]
 [3146.]
 [3786.]
 [3856.]
 [3906.]
 [3820.]
 [4388.]
 [4292.]
 [4646.]
 [4066.]
 [4008.]
 [4394.]]
[[3422.]
 [2678.]
 [2772.]
 [3148.]
 [2184.]
 [1140.]
 [1246.]
 [1892.]
 [2040.]
 [2334.]
 [3132.]
 [3114.]
 [3434.]
 [3600.]
 [3458.]
 [4056.]
 [3622.

 [4100.]]
[[6250.]
 [6250.]
 [5250.]
 [6350.]
 [6500.]
 [7800.]
 [5650.]
 [4450.]
 [5600.]
 [4400.]
 [7500.]
 [6800.]
 [5050.]
 [4400.]
 [5500.]
 [5450.]
 [5350.]
 [4800.]
 [6600.]
 [6200.]
 [5850.]
 [3850.]
 [5800.]
 [5800.]
 [3450.]
 [6350.]
 [4450.]]
[[7800.]
 [5650.]
 [6500.]
 [7250.]
 [5050.]
 [6700.]
 [5650.]
 [5650.]
 [5600.]
 [4800.]
 [5700.]
 [5900.]
 [6850.]
 [6100.]
 [5700.]
 [6500.]
 [6000.]
 [5800.]
 [6600.]
 [7550.]
 [5750.]
 [5100.]
 [6450.]
 [5400.]
 [5450.]
 [6500.]
 [6400.]]
[[9200.]
 [9650.]
 [8300.]
 [9600.]
 [7950.]
 [8750.]
 [9600.]
 [8850.]
 [8500.]
 [7700.]
 [7450.]
 [9100.]
 [7800.]
 [8500.]
 [8300.]
 [8400.]
 [8150.]
 [9100.]
 [8850.]
 [9200.]
 [9650.]
 [6750.]
 [6700.]
 [8900.]
 [7200.]
 [9550.]
 [8350.]]
[[4260.]
 [4960.]
 [3420.]
 [4180.]
 [3860.]
 [3960.]
 [5000.]
 [4100.]
 [4140.]
 [3780.]
 [4520.]
 [4740.]
 [3880.]
 [4180.]
 [4280.]
 [4460.]
 [4080.]
 [5100.]
 [4020.]
 [4560.]
 [4640.]
 [3920.]
 [4660.]
 [4240.]
 [3940.]
 [5000.]
 [4380.]]
[[5960.]
 [696

[[2830.]
 [8080.]
 [4520.]
 [5710.]
 [8130.]
 [3890.]
 [4650.]
 [3500.]
 [6550.]
 [2760.]
 [3690.]
 [6880.]
 [3760.]
 [3860.]
 [4050.]
 [6000.]
 [4130.]
 [2850.]
 [4960.]
 [1910.]
 [3150.]
 [4620.]
 [3530.]
 [2070.]
 [3180.]
 [4700.]
 [5030.]
 [5990.]
 [4300.]
 [3080.]
 [3470.]
 [3440.]
 [4170.]
 [3670.]
 [3010.]
 [4960.]
 [2230.]
 [3580.]
 [5050.]
 [2430.]
 [2870.]
 [2280.]
 [2570.]
 [3450.]
 [2380.]
 [2980.]
 [3290.]
 [3560.]
 [2020.]
 [3600.]
 [3010.]
 [2850.]
 [2530.]
 [1910.]
 [3100.]
 [1960.]
 [2590.]
 [2510.]
 [3010.]
 [2090.]
 [2050.]
 [2390.]
 [2690.]
 [2810.]
 [3320.]
 [2570.]
 [1810.]
 [2180.]
 [1710.]
 [2710.]
 [2700.]
 [3660.]
 [2640.]
 [3090.]
 [2150.]
 [1780.]
 [2020.]
 [2360.]
 [2290.]
 [2250.]
 [2040.]
 [1860.]
 [2030.]
 [2020.]]
[[1302.]
 [1822.]
 [1308.]
 [2030.]
 [2824.]
 [1342.]
 [1562.]
 [1278.]
 [2340.]
 [1826.]
 [1412.]
 [3068.]
 [1448.]
 [1202.]
 [2094.]
 [2408.]
 [2344.]
 [2386.]
 [3020.]
 [1990.]
 [2570.]
 [3664.]
 [2272.]
 [1596.]
 [3282.]
 [3870.]
 [3950.]


 [4422.1]]
[[4100.]
 [5520.]
 [5220.]
 [5640.]
 [4600.]
 [4440.]
 [4240.]
 [3600.]
 [4280.]
 [4280.]
 [5180.]
 [5320.]
 [4500.]
 [5720.]
 [5780.]
 [5680.]
 [5180.]
 [4560.]
 [4400.]
 [3820.]
 [4400.]
 [4960.]
 [5400.]
 [5460.]
 [5240.]
 [4880.]
 [5260.]
 [5160.]
 [4200.]
 [5000.]
 [4340.]
 [4120.]
 [4520.]
 [4160.]
 [4600.]
 [5620.]
 [3960.]
 [4220.]
 [4900.]
 [4820.]
 [4060.]
 [4200.]
 [2900.]
 [3700.]
 [4280.]
 [3760.]
 [4320.]
 [5020.]
 [3460.]
 [4480.]
 [4740.]
 [4160.]
 [4000.]
 [3780.]
 [3280.]
 [3280.]
 [4180.]
 [3480.]
 [4820.]
 [4920.]
 [3160.]
 [4400.]
 [4160.]
 [4040.]
 [4020.]
 [3560.]
 [3180.]
 [3140.]
 [3780.]
 [3440.]
 [4100.]
 [4440.]
 [3280.]
 [4220.]
 [3900.]
 [3820.]
 [4200.]
 [3160.]
 [3040.]
 [2900.]
 [3260.]
 [3500.]
 [3380.]
 [4380.]
 [3400.]
 [4120.]
 [3860.]
 [3860.]
 [3820.]
 [3140.]
 [2780.]
 [3120.]
 [3620.]
 [3240.]
 [3300.]
 [4340.]
 [3360.]
 [3700.]
 [3880.]
 [3560.]
 [3800.]]
[[ 6231.]
 [ 6468.]
 [ 7149.]
 [ 7300.]
 [ 8058.]
 [ 4713.]
 [ 6426.]
 [ 8148.]

[[4662.]
 [5668.]
 [6461.]
 [6936.]
 [6170.]
 [5969.]
 [3798.]
 [3709.]
 [3912.]
 [3876.]
 [4272.]
 [5328.]
 [5015.]
 [5732.]
 [6542.]
 [6889.]
 [5387.]
 [5418.]
 [5524.]
 [4194.]
 [4606.]
 [4031.]
 [4122.]
 [4988.]
 [4733.]
 [5783.]
 [6757.]
 [6463.]
 [6041.]
 [6245.]
 [4674.]
 [4203.]
 [4754.]
 [4172.]
 [4656.]
 [4982.]
 [4827.]
 [6295.]
 [6357.]
 [6685.]
 [6114.]
 [6714.]
 [5989.]
 [3758.]
 [4790.]
 [4599.]
 [4502.]
 [4908.]
 [5127.]
 [6475.]
 [6477.]
 [6692.]
 [6505.]
 [5366.]
 [5163.]
 [4079.]
 [4063.]
 [4700.]
 [4932.]
 [5265.]
 [5541.]
 [6545.]
 [6962.]
 [6833.]
 [6773.]
 [5729.]
 [4351.]
 [4405.]
 [5116.]
 [4367.]
 [4770.]
 [5557.]
 [5526.]
 [6099.]
 [6696.]
 [6731.]
 [6052.]
 [5677.]
 [4451.]
 [4773.]
 [6224.]
 [5165.]
 [4973.]
 [5658.]
 [5729.]
 [6874.]
 [7771.]
 [6991.]
 [6681.]
 [6136.]
 [6650.]]
[[1813.]
 [2832.]
 [2774.]
 [3165.]
 [2822.]
 [2404.]
 [1549.]
 [1893.]
 [1876.]
 [1680.]
 [2132.]
 [2435.]
 [2507.]
 [2524.]
 [3152.]
 [2944.]
 [2609.]
 [1473.]
 [1294.]
 [1529.]


[[3833.]
 [4019.]
 [4496.]
 [4006.]
 [3867.]
 [4331.]
 [3671.]
 [3932.]
 [3945.]
 [4010.]
 [3962.]
 [4069.]
 [4124.]
 [4277.]
 [4191.]
 [4021.]
 [4068.]
 [4176.]
 [4268.]
 [4271.]
 [4326.]
 [4263.]
 [4326.]
 [4405.]
 [4349.]
 [4330.]
 [4327.]
 [4446.]
 [4470.]
 [4672.]
 [4602.]
 [4461.]
 [4462.]
 [4646.]
 [4519.]
 [4562.]
 [4625.]
 [4850.]
 [4650.]
 [4592.]
 [4583.]
 [4574.]
 [4989.]
 [4705.]
 [4700.]
 [4728.]
 [4618.]
 [4634.]
 [4679.]
 [4630.]
 [4711.]
 [4628.]
 [4620.]
 [4538.]
 [4338.]
 [4436.]
 [4692.]
 [4483.]
 [4492.]
 [4586.]
 [4657.]
 [4613.]
 [4682.]
 [4636.]
 [4656.]
 [4663.]
 [4822.]
 [4891.]
 [4806.]
 [4803.]
 [4863.]
 [4968.]
 [4964.]
 [5024.]
 [5039.]
 [5154.]
 [5089.]
 [5255.]
 [5310.]
 [5082.]
 [5067.]
 [5266.]
 [5327.]
 [5356.]
 [5400.]
 [5441.]
 [5416.]
 [5594.]
 [5621.]
 [5668.]
 [5663.]
 [5775.]]
[[4752. ]
 [4743.5]
 [4770. ]
 [4808.5]
 [4793. ]
 [4854. ]
 [4862.5]
 [4997.5]
 [4975.5]
 [5014. ]
 [5037.5]
 [5062.5]
 [5070. ]
 [5101.5]
 [5104. ]
 [5119. ]
 [5141. ]
 

[[5025.]
 [5080.]
 [5125.]
 [5210.]
 [5185.]
 [5225.]
 [5360.]
 [5390.]
 [5420.]
 [5520.]
 [5595.]
 [5635.]
 [5685.]
 [5740.]
 [5630.]
 [5595.]
 [5600.]
 [5635.]
 [5640.]
 [5610.]
 [5630.]
 [5715.]
 [5750.]
 [5860.]
 [5800.]
 [5730.]
 [5650.]
 [5625.]
 [5675.]
 [5785.]
 [5805.]
 [5770.]
 [5765.]
 [5630.]
 [5795.]
 [5880.]
 [5945.]
 [6035.]
 [6055.]
 [6060.]
 [6035.]
 [6050.]
 [6070.]
 [6050.]
 [6035.]
 [6000.]
 [5950.]
 [5980.]
 [5915.]
 [5960.]
 [6035.]
 [6095.]
 [6115.]
 [6135.]
 [6180.]
 [6320.]
 [6380.]
 [6480.]
 [6535.]
 [6625.]
 [6750.]
 [6770.]
 [6835.]
 [7005.]
 [7155.]
 [7185.]
 [7235.]
 [7300.]
 [7425.]
 [7550.]
 [7675.]
 [7780.]
 [7905.]
 [7910.]
 [8030.]
 [8100.]
 [8225.]
 [8380.]
 [8535.]
 [8620.]]
[[ 3352.]
 [ 3372.]
 [ 3464.]
 [ 3460.]
 [ 3584.]
 [ 3524.]
 [ 3604.]
 [ 3720.]
 [ 3848.]
 [ 3876.]
 [ 3864.]
 [ 3952.]
 [ 4028.]
 [ 4064.]
 [ 4148.]
 [ 4224.]
 [ 4288.]
 [ 4380.]
 [ 4524.]
 [ 4612.]
 [ 4604.]
 [ 4780.]
 [ 4972.]
 [ 4940.]
 [ 4940.]
 [ 4984.]
 [ 4864.]
 [ 4728.]

[[4585.]
 [4730.]
 [4690.]
 [4905.]
 [4995.]
 [4865.]
 [4900.]
 [4950.]
 [4930.]
 [4875.]
 [5010.]
 [4970.]
 [4940.]
 [5075.]
 [5030.]
 [5050.]
 [5125.]
 [5115.]
 [5040.]
 [5050.]
 [5115.]
 [5195.]
 [5190.]
 [5160.]
 [5160.]
 [5115.]
 [5105.]
 [5135.]
 [5040.]
 [5065.]
 [5325.]
 [5015.]
 [5050.]
 [5145.]
 [4990.]
 [5010.]
 [5085.]
 [5015.]
 [5020.]
 [5055.]
 [5060.]
 [4855.]
 [5265.]
 [5235.]
 [5115.]
 [5050.]
 [5095.]
 [5165.]
 [5125.]
 [5085.]
 [5265.]
 [5000.]
 [5035.]
 [5035.]
 [4865.]
 [4870.]
 [4790.]
 [4715.]
 [4660.]
 [4705.]
 [4610.]
 [4670.]
 [4690.]
 [4660.]
 [4590.]
 [4690.]
 [4610.]
 [4630.]
 [4715.]
 [4730.]
 [4850.]
 [4620.]
 [4700.]
 [4675.]
 [4660.]
 [4665.]
 [4720.]
 [4640.]
 [4725.]
 [4750.]
 [4670.]
 [4580.]
 [4670.]
 [4565.]
 [4635.]
 [4705.]
 [4725.]
 [4705.]
 [4910.]
 [4895.]
 [4995.]
 [4960.]]
[[4860.]
 [4750.]
 [4760.]
 [4830.]
 [4870.]
 [4870.]
 [4895.]
 [4825.]
 [4940.]
 [4925.]
 [5015.]
 [5020.]
 [5070.]
 [5115.]
 [4985.]
 [5090.]
 [4990.]
 [5025.]
 [5245.]


[[4505.]
 [4535.]
 [4475.]
 [4645.]
 [4695.]
 [4780.]
 [4790.]
 [4855.]
 [4900.]
 [4950.]
 [5005.]
 [5055.]
 [5055.]
 [5035.]
 [5045.]
 [5085.]
 [5110.]
 [5115.]
 [5100.]
 [5140.]
 [5120.]
 [5080.]
 [5010.]
 [4965.]
 [4970.]
 [5025.]
 [5020.]
 [5030.]
 [5055.]
 [5085.]
 [5055.]
 [5110.]
 [5170.]
 [5135.]
 [5085.]
 [5070.]
 [4955.]
 [5000.]
 [5055.]
 [4970.]
 [5070.]
 [4995.]
 [5120.]
 [5110.]
 [5190.]
 [5025.]
 [5115.]
 [5000.]
 [5010.]
 [5030.]
 [4975.]
 [4995.]
 [4940.]
 [5000.]
 [4915.]
 [4825.]
 [4800.]
 [4750.]
 [4795.]
 [4805.]
 [4830.]
 [4865.]
 [4895.]
 [4870.]
 [4905.]
 [4845.]
 [4905.]
 [4890.]
 [4895.]
 [4955.]
 [4940.]
 [4950.]
 [4935.]
 [4935.]
 [4955.]
 [5010.]
 [5005.]
 [5060.]
 [5045.]
 [5065.]
 [5055.]
 [5130.]
 [5055.]
 [5065.]
 [5080.]
 [5045.]
 [5055.]
 [5080.]
 [5085.]
 [5085.]
 [5110.]
 [5105.]]
[[4720.]
 [4730.]
 [4735.]
 [4825.]
 [4765.]
 [4835.]
 [4845.]
 [4895.]
 [4900.]
 [4900.]
 [4935.]
 [5005.]
 [5065.]
 [5110.]
 [5080.]
 [5025.]
 [5100.]
 [5125.]
 [5165.]


[[4737.45]
 [4697.75]
 [4521.1 ]
 [4684.45]
 [4638.7 ]
 [4499.15]
 [4646.65]
 [4744.25]
 [4848.45]
 [4861.7 ]
 [4954.4 ]
 [5030.55]
 [5068.35]
 [5027.1 ]
 [4957.3 ]
 [5156.45]
 [5218.  ]
 [5274.05]
 [5243.5 ]
 [5198.25]
 [5192.95]
 [5223.25]
 [5287.25]
 [5338.9 ]
 [5350.9 ]
 [5427.75]
 [5498.3 ]
 [5472.65]
 [5514.55]
 [5634.5 ]
 [5732.6 ]
 [5812.55]
 [5846.8 ]
 [5933.4 ]
 [6002.  ]
 [6064.1 ]
 [6077.35]
 [6110.35]
 [6047.95]
 [6034.65]
 [6078.  ]
 [6085.8 ]
 [5938.15]
 [5933.35]
 [5971.6 ]
 [5962.25]
 [6013.15]
 [6048.85]
 [6092.85]
 [6221.15]
 [6186.8 ]
 [6202.1 ]
 [6163.5 ]
 [6083.3 ]
 [6147.2 ]
 [6042.3 ]
 [5849.45]
 [5863.5 ]
 [5860.95]
 [5805.75]
 [5832.5 ]
 [5866.4 ]
 [5943.6 ]
 [5956.6 ]
 [5939.3 ]
 [5986.95]
 [5881.6 ]
 [5891.  ]
 [5948.65]
 [6078.75]
 [6058.8 ]
 [6059.85]
 [6097.95]
 [6089.65]
 [6038.45]
 [6044.4 ]
 [6090.  ]
 [6176.  ]
 [6237.95]
 [6320.6 ]
 [6416.75]
 [6443.95]
 [6441.55]
 [6465.9 ]
 [6401.25]
 [6412.15]
 [6470.8 ]
 [6568.  ]
 [6701.15]
 [6787.85]
 [6855.25]

[[4239.2 ]
 [4603.4 ]
 [4874.4 ]
 [4675.4 ]
 [4577.45]
 [4522.8 ]
 [4348.3 ]
 [4767.95]
 [4906.85]
 [4778.  ]
 [4827.3 ]
 [5134.4 ]
 [4752.6 ]
 [4981.7 ]
 [5318.25]
 [5155.1 ]
 [5033.8 ]
 [4914.45]
 [4747.  ]
 [5069.3 ]
 [5300.1 ]
 [5166.6 ]
 [5199.65]
 [5546.65]
 [5060.9 ]
 [5426.25]
 [5653.65]
 [5475.8 ]
 [5371.55]
 [5311.65]
 [5164.2 ]
 [5482.5 ]
 [5637.35]
 [5568.8 ]
 [5594.4 ]
 [5829.45]
 [5248.85]
 [5621.35]
 [5826.6 ]
 [5716.2 ]
 [5555.55]
 [5367.75]
 [5283.2 ]
 [5604.95]
 [5860.25]
 [5671.3 ]
 [5727.2 ]
 [5980.05]
 [5484.7 ]
 [6105.8 ]
 [6372.15]
 [6355.65]
 [6116.7 ]
 [5680.95]
 [5455.95]
 [5704.8 ]
 [5796.15]
 [5712.6 ]
 [5843.65]
 [6017.6 ]
 [5552.3 ]
 [5945.15]
 [6181.95]
 [6122.5 ]
 [5930.7 ]
 [5557.05]
 [5318.25]
 [5673.85]
 [5946.4 ]
 [5840.8 ]
 [5932.9 ]
 [6308.4 ]
 [5826.2 ]
 [5998.45]
 [6407.55]
 [6204.3 ]
 [6041.85]
 [5875.75]
 [5625.45]
 [5987.85]
 [6264.7 ]
 [6010.95]
 [6071.75]
 [6471.2 ]
 [5879.4 ]
 [6206.1 ]
 [6519.15]
 [6394.95]
 [6183.3 ]
 [5902.15]
 [5675.8 ]

[[6229.]
 [6453.]
 [6731.]
 [6706.]
 [6713.]
 [6831.]
 [6940.]
 [7281.]
 [7377.]
 [7155.]
 [7137.]
 [7178.]
 [6855.]
 [7000.]
 [7255.]
 [7450.]
 [7657.]
 [7362.]
 [7459.]
 [7553.]
 [7683.]
 [7689.]
 [7803.]
 [7731.]
 [7571.]
 [7971.]
 [8039.]
 [8088.]
 [8230.]
 [8431.]
 [8550.]
 [8325.]
 [8040.]
 [8327.]
 [8399.]
 [8401.]
 [8148.]
 [8138.]
 [7996.]
 [7853.]
 [7967.]
 [8295.]
 [7990.]
 [8186.]
 [8710.]
 [8378.]
 [8207.]
 [8494.]
 [8712.]
 [8680.]
 [8571.]
 [8709.]
 [8447.]
 [8264.]
 [8351.]
 [8239.]
 [7940.]
 [8285.]
 [8314.]
 [8270.]
 [8473.]
 [8548.]
 [8647.]
 [8693.]
 [8534.]
 [8403.]
 [8660.]
 [8632.]
 [8704.]
 [8677.]
 [8567.]
 [8625.]
 [8648.]
 [8532.]
 [8500.]
 [8520.]
 [8612.]
 [8683.]
 [8680.]
 [8770.]
 [8705.]
 [9159.]
 [8608.]
 [8626.]
 [8215.]
 [8624.]
 [8690.]
 [8700.]
 [8944.]
 [8989.]
 [8873.]
 [8889.]]
[[6650. ]
 [6703.5]
 [6756.5]
 [6547. ]
 [6677. ]
 [6593.5]
 [6639.5]
 [6738. ]
 [6741. ]
 [6779.5]
 [6789. ]
 [6838. ]
 [6817.5]
 [6809. ]
 [6860.5]
 [6747.5]
 [6748. ]
 

[[7039.]
 [7187.]
 [6998.]
 [6969.]
 [7086.]
 [7095.]
 [7285.]
 [7083.]
 [7151.]
 [7116.]
 [7149.]
 [7144.]
 [7128.]
 [7183.]
 [7140.]
 [7121.]
 [7154.]
 [7155.]
 [7166.]
 [7162.]
 [7145.]
 [7181.]
 [7300.]
 [7218.]
 [7289.]
 [7319.]
 [7406.]
 [7468.]
 [7450.]
 [7493.]
 [7542.]
 [7584.]
 [7647.]
 [7707.]
 [7819.]
 [7775.]
 [7871.]
 [7815.]
 [7843.]
 [7843.]
 [7814.]
 [7779.]
 [7745.]
 [7730.]
 [7740.]
 [7783.]
 [7743.]
 [7803.]
 [7823.]
 [7863.]
 [7962.]
 [8085.]
 [8091.]
 [8180.]
 [8214.]
 [8219.]
 [8143.]
 [8117.]
 [8048.]
 [8020.]
 [7972.]
 [7956.]
 [7879.]
 [7844.]
 [7915.]
 [7939.]
 [7850.]
 [7877.]
 [7835.]
 [7821.]
 [7838.]
 [7863.]
 [7841.]
 [7905.]
 [7878.]
 [7799.]
 [7845.]
 [7768.]
 [7773.]
 [7757.]
 [7783.]
 [7838.]
 [7724.]
 [7687.]
 [7692.]
 [7621.]
 [7601.]
 [7594.]
 [7518.]
 [7493.]
 [7556.]
 [7509.]]
[[3844. ]
 [3743. ]
 [3665.6]
 [3615.8]
 [3631.8]
 [3695.4]
 [3647.6]
 [3572.8]
 [3557.6]
 [3568. ]
 [3543.8]
 [3544.8]
 [3566.8]
 [3599.2]
 [3645.2]
 [3696.4]
 [3763. ]
 

 [9649.]]
[[5166.5]
 [5165.5]
 [5120. ]
 [5109. ]
 [5125.5]
 [5142.5]
 [5193.5]
 [5266. ]
 [5364. ]
 [5354. ]
 [5419. ]
 [5421. ]
 [5420. ]
 [5469. ]
 [5487.5]
 [5487.5]
 [5489. ]
 [5596. ]
 [5602.5]
 [5616. ]
 [5631.5]
 [5683.5]
 [5728.5]
 [5769. ]
 [5830. ]
 [5918. ]
 [6002. ]
 [6074.5]
 [6154. ]
 [6233. ]
 [6215.5]
 [6210.5]
 [6227. ]
 [6240.5]
 [6343. ]
 [6466.5]
 [6543.5]
 [6619. ]
 [6641. ]
 [6667.5]
 [6645.5]
 [6637. ]
 [6694. ]
 [6696.5]
 [6663.5]
 [6634. ]
 [6674. ]
 [6721.5]
 [6746. ]
 [6703.5]
 [6712. ]
 [6696. ]
 [6691.5]
 [6746. ]
 [6800. ]
 [6859. ]
 [6864.5]
 [6816. ]
 [6768.5]
 [6702.5]
 [6674.5]
 [6589.5]
 [6623.5]
 [6696. ]
 [6733.5]
 [6772. ]
 [6809.5]
 [6778.5]
 [6779.5]
 [6800. ]
 [6832. ]
 [6759.5]
 [6790. ]
 [6852.5]
 [6853.5]
 [6883.5]
 [6859.5]
 [6693.5]
 [6714.5]
 [6727.5]
 [6733.5]
 [6736.5]
 [6756.5]
 [6752. ]
 [6798. ]
 [6857. ]
 [6800. ]
 [6789.5]
 [6760. ]
 [6743.5]
 [6697. ]
 [6737.5]]
[[5132.2]
 [5069.6]
 [5042.6]
 [5057. ]
 [5055.6]
 [5148.8]
 [5127.2]

[[5796.]
 [6126.]
 [6286.]
 [6034.]
 [5835.]
 [5724.]
 [5623.]
 [5625.]
 [5938.]
 [5658.]
 [5835.]
 [5843.]
 [5797.]
 [5782.]
 [5862.]
 [6039.]
 [5998.]
 [5456.]
 [6002.]
 [6288.]
 [5601.]
 [6059.]
 [6046.]
 [6045.]
 [5894.]
 [6191.]
 [6342.]
 [6081.]
 [6365.]
 [6426.]
 [6742.]
 [6312.]
 [6506.]
 [6615.]
 [6356.]
 [6344.]
 [6283.]
 [6521.]
 [6412.]
 [6653.]
 [6541.]
 [6605.]
 [6338.]
 [6475.]
 [6646.]
 [6284.]
 [6534.]
 [6667.]
 [6424.]
 [6412.]
 [6473.]
 [6290.]
 [6710.]
 [6356.]
 [5966.]
 [6208.]
 [6191.]
 [6476.]
 [6557.]
 [6282.]
 [6587.]
 [6765.]
 [6714.]
 [6742.]
 [6805.]
 [6749.]
 [6272.]
 [6693.]
 [6615.]
 [7012.]
 [6703.]
 [6759.]
 [7100.]
 [6908.]
 [6974.]
 [7295.]
 [7359.]
 [7184.]
 [7313.]
 [7365.]
 [7105.]
 [7215.]
 [7148.]
 [7386.]
 [7554.]
 [7600.]
 [7606.]
 [7594.]
 [7756.]
 [7875.]
 [7591.]
 [7624.]]
[[3355.2]
 [3052.1]
 [3399.8]
 [3177.3]
 [3415.4]
 [3340.7]
 [3221.7]
 [3156.3]
 [3381.3]
 [3622.7]
 [3650. ]
 [3682.4]
 [3855.5]
 [3491.2]
 [3444.1]
 [3609.2]
 [3597.8]
 

[[5785.]
 [5165.]
 [4665.]
 [6900.]
 [5180.]
 [4690.]
 [5540.]
 [5935.]
 [5990.]
 [5730.]
 [5205.]
 [4875.]
 [5225.]
 [4520.]
 [4680.]
 [5460.]
 [3815.]
 [4385.]
 [5040.]
 [5245.]
 [5505.]
 [5090.]
 [5045.]
 [4630.]
 [4550.]
 [4900.]
 [4500.]
 [4010.]
 [4460.]
 [4460.]
 [4780.]
 [4580.]
 [5535.]
 [4180.]
 [4900.]
 [4910.]
 [4245.]
 [4825.]
 [4245.]
 [5005.]
 [4300.]
 [4095.]
 [5675.]
 [4800.]
 [5030.]
 [5065.]
 [5475.]
 [5435.]
 [5465.]
 [5830.]
 [4935.]
 [6290.]
 [5420.]
 [4955.]
 [6845.]
 [6585.]
 [7320.]
 [7360.]
 [7820.]
 [6735.]
 [7210.]
 [7195.]
 [7070.]
 [8385.]
 [6825.]
 [6860.]
 [8685.]
 [8235.]
 [9245.]
 [8575.]
 [7280.]
 [8260.]
 [8240.]
 [7945.]
 [7245.]
 [7820.]
 [7335.]
 [6555.]
 [7545.]
 [6505.]
 [7475.]
 [6715.]
 [6790.]
 [6265.]
 [6030.]
 [6290.]
 [7390.]
 [5920.]
 [5495.]
 [4990.]
 [5040.]]
[[4060.]
 [3660.]
 [3670.]
 [4740.]
 [3700.]
 [3600.]
 [3570.]
 [3850.]
 [3940.]
 [4250.]
 [3610.]
 [3890.]
 [3730.]
 [3420.]
 [3200.]
 [3900.]
 [3170.]
 [3000.]
 [4000.]
 [3940.]


[[5450.]
 [4550.]
 [5850.]
 [5900.]
 [5950.]
 [5550.]
 [5550.]
 [5950.]
 [6100.]
 [5650.]
 [6000.]
 [5800.]
 [5300.]
 [4800.]
 [6000.]
 [6000.]
 [6100.]
 [5650.]
 [5600.]
 [6000.]
 [6150.]
 [5750.]
 [6050.]
 [5900.]
 [5500.]
 [5050.]
 [6300.]
 [6350.]
 [6550.]
 [6100.]
 [6300.]
 [6700.]
 [6450.]
 [6550.]
 [6400.]
 [6650.]
 [5700.]
 [5450.]
 [6500.]
 [6750.]
 [6900.]
 [6500.]
 [6750.]
 [6950.]
 [6950.]
 [6450.]
 [6850.]
 [6550.]
 [5800.]
 [5650.]
 [6650.]
 [6900.]
 [7000.]
 [6650.]
 [6750.]
 [7000.]
 [7300.]
 [6600.]
 [6800.]
 [6800.]
 [6050.]
 [5700.]
 [6750.]
 [6800.]
 [6900.]
 [6550.]]
[[4780.]
 [4985.]
 [5270.]
 [5255.]
 [5330.]
 [4980.]
 [5020.]
 [5335.]
 [5290.]
 [5420.]
 [5585.]
 [5745.]
 [5210.]
 [5515.]
 [5740.]
 [5695.]
 [5815.]
 [5390.]
 [5460.]
 [5650.]
 [5850.]
 [5810.]
 [6050.]
 [6240.]
 [5750.]
 [5920.]
 [6165.]
 [6340.]
 [6370.]
 [6055.]
 [6030.]
 [6310.]
 [6350.]
 [6375.]
 [6490.]
 [6650.]
 [6095.]
 [6270.]
 [6570.]
 [6680.]
 [6660.]
 [6270.]
 [6210.]
 [6410.]
 [6405.]


[[3863.02]
 [3903.16]
 [4046.7 ]
 [3983.92]
 [4115.5 ]
 [4485.7 ]
 [4245.82]
 [4068.68]
 [4219.12]
 [4650.24]
 [4334.82]
 [4471.36]
 [4357.22]
 [4318.74]
 [4435.06]
 [4588.56]
 [4600.44]
 [4720.92]
 [4531.26]
 [4510.52]
 [4550.08]
 [4880.12]
 [4677.72]
 [4797.34]
 [4721.5 ]
 [4677.64]
 [4872.14]
 [4767.4 ]
 [4876.06]
 [5018.9 ]
 [4828.26]
 [4615.9 ]
 [4768.7 ]
 [5149.96]
 [4685.72]
 [4781.18]
 [4524.6 ]
 [4503.84]
 [4574.08]
 [4528.82]
 [4610.32]
 [4739.82]
 [4520.92]
 [5156.58]
 [4577.88]
 [4642.48]
 [4709.5 ]
 [4781.28]
 [4811.22]
 [4889.  ]
 [4861.64]
 [4917.02]
 [5045.58]
 [5240.04]
 [5169.42]
 [5201.8 ]
 [5001.38]
 [5036.96]
 [5099.7 ]
 [5136.26]
 [5172.72]
 [5239.82]
 [5290.56]
 [5481.22]
 [5439.84]
 [5787.88]
 [5449.62]
 [5430.72]
 [5480.26]
 [5496.6 ]
 [5547.08]
 [5674.58]
 [5641.38]
 [5763.6 ]
 [6074.48]
 [5778.34]
 [6033.76]
 [6244.68]
 [6050.62]
 [6152.3 ]
 [6240.74]
 [6222.66]
 [6300.48]
 [6717.38]
 [6407.6 ]
 [6552.58]
 [6728.44]
 [6545.92]
 [6828.14]
 [7016.64]
 [6964.72]

[[7731.2]
 [7774. ]
 [7732.2]
 [7748.2]
 [7891.2]
 [8662.6]
 [8258. ]
 [7937.8]
 [7840.8]
 [7856.2]
 [7924.2]
 [7920.2]
 [7895.8]
 [7977.2]
 [7979.2]
 [8074. ]
 [8324. ]
 [9203.8]
 [8773.2]
 [8446.8]
 [8369.2]
 [8346. ]
 [8363.6]
 [8386.2]
 [8348.2]
 [8402. ]
 [8355.6]
 [8471.8]
 [8729.4]
 [9760.6]
 [8287.8]
 [7917.8]
 [7762. ]
 [7747.8]
 [7820. ]
 [7784.2]
 [7778.4]
 [7871.6]
 [7799.6]
 [7763. ]
 [7963.2]
 [8830.8]
 [8363.4]
 [8017.8]
 [7988.2]
 [7902.6]
 [7930. ]
 [7941.8]
 [7818.6]
 [7896.2]
 [7777.8]
 [7625.4]
 [7799.8]
 [8692.8]
 [8142.8]
 [7692. ]
 [7495.6]
 [7350. ]
 [7060. ]
 [6931.4]
 [6856. ]
 [6970. ]
 [6805. ]
 [6816. ]
 [7074. ]
 [7966.4]
 [7462.2]
 [7170.2]
 [7074. ]
 [7107.8]
 [7146.2]
 [7083. ]
 [6929.2]
 [7188.6]
 [7185. ]
 [7288.2]
 [7335.6]
 [8415.8]
 [8011.4]
 [7692.4]
 [7606. ]
 [7643.6]
 [7736.2]
 [7762.6]
 [7808.6]
 [7937.6]
 [7968.4]
 [8062. ]
 [8409.4]
 [9476.4]
 [8997.2]]
[[5411.8]
 [5566.6]
 [5486.9]
 [5548.1]
 [5586.2]
 [5663.5]
 [5660.6]
 [5651.3]
 [5667.8]

[[4391.5]
 [4446. ]
 [4506. ]
 [4590.5]
 [4651. ]
 [4694. ]
 [4761. ]
 [4783. ]
 [4830.5]
 [4859. ]
 [4849.5]
 [4857. ]
 [4847.5]
 [4818.5]
 [4793. ]
 [4762.5]
 [4708.5]
 [4679. ]
 [4678.5]
 [4673.5]
 [4713. ]
 [4732.5]
 [4730. ]
 [4765.5]
 [4774. ]
 [4736.5]
 [4686.5]
 [4668. ]
 [4665.5]
 [4626.5]
 [4573.5]
 [4504. ]
 [4477.5]
 [4413. ]
 [4310.5]
 [4307. ]
 [4326.5]
 [4343. ]
 [4360.5]
 [4392. ]
 [4435.5]
 [4452. ]
 [4468.5]
 [4486. ]
 [4534.5]
 [4555.5]
 [4535. ]
 [4564.5]
 [4578.5]
 [4588.5]
 [4586. ]
 [4588. ]
 [4599.5]
 [4587. ]
 [4592. ]
 [4628. ]
 [4715.5]
 [4778.5]
 [4826.5]
 [4902.5]
 [4952.5]
 [4980.5]
 [5003.5]
 [5066.5]
 [5141. ]
 [5190. ]
 [5271.5]
 [5383.5]
 [5495. ]
 [5569.5]
 [5603. ]
 [5652.5]
 [5691. ]
 [5733.5]
 [5792.5]
 [5850.5]
 [5905.5]
 [5905.5]
 [5888.5]
 [5893.5]
 [5922.5]
 [5946.5]
 [5979. ]
 [6022.5]
 [6025. ]
 [6034.5]
 [6032. ]
 [6038.5]
 [6072. ]
 [6066. ]
 [6070.5]
 [6078.5]]
[[4426.5]
 [4409.5]
 [4390. ]
 [4361. ]
 [4319.5]
 [4295. ]
 [4297.5]
 [4275. ]

 [8220.5]]
[[3755.8]
 [3723.6]
 [3797.2]
 [4105.4]
 [4127. ]
 [4095. ]
 [4241.4]
 [4487.4]
 [4546. ]
 [4445. ]
 [4626.2]
 [4944. ]
 [5121.8]
 [5366.8]
 [5155.4]
 [4529.4]
 [3764.6]
 [3710. ]
 [3844. ]
 [3980.6]
 [4257.6]
 [4190.8]
 [3951.4]
 [4226.6]
 [4207.4]
 [4062. ]
 [4194.2]
 [4397.8]
 [4339.4]
 [4512.6]
 [4753. ]
 [5028.4]
 [4913.8]
 [5012.6]
 [5251.8]
 [5362. ]
 [5521.4]
 [6148.8]
 [6308.4]
 [5957.8]
 [5448.2]
 [5521.4]
 [5418. ]
 [5228.4]
 [5489.6]
 [5470.4]
 [5547.8]
 [5682.8]
 [5539.4]
 [4801.6]
 [4495.2]
 [4329.4]
 [4377.4]
 [4657.8]
 [4827.4]
 [5407.2]
 [5358.2]
 [5477.8]
 [5694.4]
 [5924.6]
 [5886.4]
 [5911.4]
 [5902.4]
 [6288.4]
 [6317.2]
 [6254.6]
 [6807. ]
 [6966.2]
 [6934.6]
 [6899.6]
 [7132.4]
 [6841.4]
 [6688.8]
 [6435.4]
 [6463.8]
 [6549.2]
 [7032.8]
 [7267. ]
 [7485.4]
 [7591.4]
 [7524.4]
 [7817. ]
 [7728. ]
 [7495.4]
 [7599.6]
 [8019.6]
 [7945. ]
 [8055. ]
 [8356.6]
 [8497.6]
 [8829.4]
 [8750. ]]
[[2690.4]
 [2630. ]
 [2660.8]
 [2710.2]
 [2830. ]
 [2814. ]
 [2962.6

 [6485.9 ]]
[[5591.6 ]
 [5575.75]
 [5511.45]
 [5542.85]
 [5537.55]
 [5529.4 ]
 [5454.2 ]
 [5473.2 ]
 [5511.45]
 [5552.05]
 [5618.85]
 [5674.9 ]
 [5732.6 ]
 [5726.35]
 [5651.35]
 [5694.9 ]
 [5690.45]
 [5683.95]
 [5606.95]
 [5623.  ]
 [5643.35]
 [5695.25]
 [5711.1 ]
 [5810.45]
 [5853.3 ]
 [5836.85]
 [5773.7 ]
 [5812.5 ]
 [5815.7 ]
 [5798.9 ]
 [5739.3 ]
 [5751.15]
 [5792.2 ]
 [5817.35]
 [5851.95]
 [5935.95]
 [5975.1 ]
 [5954.6 ]
 [5874.9 ]
 [5909.7 ]
 [5908.4 ]
 [5884.9 ]
 [5801.85]
 [5815.4 ]
 [5854.65]
 [5867.95]
 [5913.85]
 [5980.25]
 [5997.7 ]
 [5958.7 ]
 [5898.05]
 [5914.95]
 [5880.55]
 [5864.35]
 [5749.5 ]
 [5757.55]
 [5781.95]
 [5833.9 ]
 [5831.2 ]
 [5914.  ]
 [5937.55]
 [5892.95]
 [5866.75]
 [5877.75]
 [5855.5 ]
 [5827.45]
 [5756.1 ]
 [5761.2 ]
 [5805.3 ]
 [5846.65]
 [5876.75]
 [5945.35]
 [5987.7 ]
 [5954.1 ]
 [5897.65]
 [5912.3 ]
 [5911.95]
 [5903.65]
 [5806.15]
 [5836.75]
 [5870.3 ]
 [5892.8 ]
 [5960.05]
 [6029.3 ]
 [6066.15]
 [6050.1 ]
 [5986.5 ]
 [6022.3 ]
 [6031.6 ]
 [6031.8 

[[4600.]
 [4610.]
 [4610.]
 [4605.]
 [4585.]
 [4625.]
 [4585.]
 [4570.]
 [4565.]
 [4585.]
 [4585.]
 [4610.]
 [4675.]
 [4600.]
 [4630.]
 [4640.]
 [4640.]
 [4625.]
 [4620.]
 [4610.]
 [4615.]
 [4595.]
 [4590.]
 [4570.]
 [4545.]
 [4520.]
 [4515.]
 [4510.]
 [4525.]
 [4525.]
 [4540.]
 [4560.]
 [4575.]
 [4560.]
 [4555.]
 [4540.]
 [4525.]
 [4530.]
 [4520.]
 [4505.]
 [4500.]
 [4500.]
 [4480.]
 [4450.]
 [4410.]
 [4400.]
 [4375.]
 [4360.]
 [4305.]
 [4315.]
 [4315.]
 [4280.]
 [4225.]
 [4195.]
 [4175.]
 [4175.]
 [4175.]
 [4145.]
 [4165.]
 [4180.]
 [4210.]
 [4215.]
 [4230.]
 [4250.]
 [4275.]
 [4260.]
 [4245.]
 [4240.]
 [4235.]
 [4235.]
 [4240.]
 [4225.]
 [4255.]
 [4195.]
 [4175.]
 [4165.]
 [4160.]
 [4160.]
 [4165.]
 [4160.]
 [4170.]
 [4140.]
 [4145.]
 [4115.]
 [4095.]
 [4065.]
 [4060.]
 [4025.]
 [4025.]
 [3985.]
 [3975.]
 [3970.]
 [3955.]]
[[6320.]
 [6370.]
 [6410.]
 [6430.]
 [6440.]
 [6450.]
 [6480.]
 [6500.]
 [6520.]
 [6530.]
 [6520.]
 [6480.]
 [6500.]
 [6510.]
 [6520.]
 [6560.]
 [6580.]
 [6620.]


[[6033. ]
 [6095.6]
 [6074.4]
 [6108. ]
 [6273.2]
 [6190.4]
 [6268. ]
 [6377.2]
 [6330.8]
 [6330.8]
 [6330.8]
 [6282.6]
 [6248.2]
 [6362.8]
 [6285.6]
 [6342.2]
 [6454.2]
 [6343.2]
 [6440.2]
 [6519.4]
 [6368.8]
 [6501.6]
 [6454.6]
 [6401. ]
 [6490.8]
 [6408. ]
 [6497.4]
 [6648.6]
 [6578.8]
 [6651.6]
 [6815.6]
 [6747.4]
 [6711.6]
 [6921.4]
 [6685.6]
 [6766.2]
 [6921.4]
 [6780.6]
 [6828. ]
 [6996.2]
 [6878. ]
 [6920.6]
 [6970.4]
 [7040. ]
 [6999. ]
 [7184. ]
 [7041.6]
 [7081.2]
 [7232.8]
 [7090. ]
 [7285. ]
 [7149.8]
 [7198.4]
 [7399.2]
 [7283.8]
 [7360.4]
 [7340.8]
 [7362. ]
 [7341.4]
 [7522.4]
 [7341.4]
 [7382.8]
 [7560. ]
 [7426.6]
 [7490.2]
 [7696.6]
 [7582.8]
 [7862.4]
 [7804.8]
 [7668.4]
 [7654. ]
 [7611.2]
 [7632.6]
 [7862.6]
 [7696.4]
 [7760.8]
 [8000.2]
 [7853.4]
 [7946.8]
 [7989.6]
 [7930.8]
 [8004. ]
 [8210.2]
 [7974.4]
 [8002.8]
 [8262.8]
 [8102.6]
 [8196.8]
 [8202.2]
 [8282.4]
 [8523.2]
 [8384.4]
 [8332.4]]
[[5287.4]
 [5287.4]
 [5320. ]
 [5339.6]
 [5421. ]
 [5397.8]
 [5420. ]

[[3100.]
 [3300.]
 [2900.]
 [3100.]
 [3200.]
 [3300.]
 [3400.]
 [3300.]
 [3300.]
 [3400.]
 [3000.]
 [2000.]
 [2600.]
 [3100.]
 [3600.]
 [4700.]
 [5000.]
 [5500.]
 [5800.]
 [6200.]
 [6600.]
 [7400.]
 [7900.]
 [8400.]
 [8400.]
 [7900.]
 [8800.]
 [8600.]
 [9200.]
 [9000.]]
[[1290.]
 [ 990.]
 [1330.]
 [1250.]
 [1480.]
 [1460.]
 [1400.]
 [1640.]
 [1370.]
 [1280.]
 [1560.]
 [1350.]
 [1390.]
 [1070.]
 [1590.]
 [1250.]
 [1660.]
 [1640.]
 [1730.]
 [1740.]
 [1590.]
 [1100.]
 [1230.]
 [1380.]
 [ 950.]
 [ 860.]
 [1060.]
 [ 930.]
 [ 780.]]
[[ 710.]
 [ 660.]
 [ 830.]
 [ 830.]
 [1500.]
 [1930.]
 [1620.]
 [2550.]
 [1730.]
 [1680.]
 [2010.]
 [1270.]
 [1670.]
 [1170.]
 [4220.]
 [1920.]
 [2510.]
 [1910.]
 [2580.]
 [2300.]
 [2200.]
 [1490.]
 [1690.]
 [2220.]
 [1470.]
 [1230.]
 [2740.]
 [2040.]
 [2110.]]
[[3679.]
 [3499.]
 [4289.]
 [5267.]
 [4305.]
 [5484.]
 [4252.]
 [5740.]
 [4825.]
 [5127.]
 [4242.]
 [4826.]
 [3287.]
 [4675.]
 [5293.]
 [4933.]
 [4598.]
 [5576.]
 [4661.]
 [4579.]
 [5617.]
 [3948.]
 [4209.

 [ 3680.]]
[[ 9280.]
 [10680.]
 [ 8840.]
 [ 6280.]
 [ 4800.]
 [ 4120.]
 [ 2720.]
 [ 3720.]
 [ 5480.]
 [ 6400.]
 [ 7720.]
 [ 8600.]
 [10080.]
 [10200.]
 [ 8800.]
 [ 6800.]
 [ 4000.]
 [ 1160.]
 [ 3400.]
 [ 3160.]
 [ 4480.]
 [ 6840.]
 [ 7840.]
 [ 9360.]
 [10440.]
 [ 9240.]
 [ 9160.]
 [ 6960.]
 [ 4320.]
 [ 5240.]
 [ 3280.]
 [ 4200.]
 [ 4600.]
 [ 6160.]
 [ 7080.]
 [ 9320.]
 [10080.]
 [ 9520.]
 [ 8320.]
 [ 6280.]
 [ 4960.]
 [ 3520.]
 [ 4600.]
 [ 3560.]
 [ 5360.]
 [ 5320.]
 [ 7960.]
 [ 9000.]
 [ 8880.]
 [ 9320.]
 [ 8360.]
 [ 5720.]
 [ 4680.]
 [ 3600.]]
[[ 8800.]
 [ 8960.]
 [ 8160.]
 [ 6120.]
 [ 5120.]
 [ 2480.]
 [ 2000.]
 [ 3640.]
 [ 5120.]
 [ 5480.]
 [ 6520.]
 [ 9240.]
 [10000.]
 [ 8720.]
 [ 8440.]
 [ 6520.]
 [ 4600.]
 [ 3720.]
 [ 1560.]
 [ 1240.]
 [ 5280.]
 [ 6880.]
 [ 7640.]
 [ 8880.]
 [ 9200.]
 [ 9640.]
 [ 8480.]
 [ 7160.]
 [ 4120.]
 [ 4000.]
 [ 4240.]
 [ 4000.]
 [ 5280.]
 [ 7200.]
 [ 8080.]
 [ 8680.]
 [10080.]
 [ 9520.]
 [ 8080.]
 [ 6840.]
 [ 4320.]
 [ 3080.]
 [ 4120.]
 [ 2800.]
 [ 4000.

In [61]:
len(m3_year)

645

In [ ]:
# Define the p, d and q parameters to take any value between 0 and 2
p = d = q = range(0, 2)

# Generate all different combinations of p, q and q triplets
pdq = list(itertools.product(p, d, q))

print(pdq)

[(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]


In [ ]:
# Brute force exploration of the best set of pdq parameters

def explore_pdq(series, pdq):
    results_aic = [sys.maxsize] * len(series)
    results = [None] * len(series)
    best_pdq = [None] * len(series)
    i = 0
    for ts in series:
        for param in pdq:
            try:
                model = ARIMA(ts, order=param)
                result = model.fit(disp=0)
                if result.aic < results_aic[i]:
                    results_aic[i] = result.aic
                    results[i] = result
                    best_pdq[i] = param
            except Exception as e:
                print(e)
                continue

        i = i + 1
    return results, best_pdq

train_year_results, best_year_pdq = explore_pdq(train_year_dfs,pdq)
train_month_results, best_month_pdq = explore_pdq(train_mont_dfs,pdq)
train_quart_results, best_quart_pdq = explore_pdq(train_quar_dfs,pdq)

The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/kalmanf/kalmanfilter.py:646: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if issubdtype(paramsdtype, float):
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/kalmanf/kalmanfilter.py:650: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  elif issubdtype(paramsdtype, complex):
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:473: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:654: RuntimeWarning: divide by zero encountered in log
  invmacoefs = -np.log((1-macoefs)/(1+macoefs))
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tools/numdiff.py:243: RuntimeWarning: invalid value encountered in subtract
  **kwargs)).imag/2./hess[i, j]
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tools/numdiff.py:243: RuntimeWarning: invalid value encountered in multiply
  **kwargs)).imag/2./hess[i, j]
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:628: RuntimeWarning: invalid value encountered in exp
  newparams = ((1-np.exp(-params))/(1+np.exp(-params))).copy()
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:629: RuntimeWarning: invalid value encountered in exp
  tmp = ((1-np.exp(-params))/(1+np.exp(-params))).copy()
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: Co

The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:585: RuntimeWarning: invalid value encountered in true_divide
  (1+np.exp(-params))).copy()
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:587: RuntimeWarning: invalid value encountered in true_divide
  (1+np.exp(-params))).copy()


SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/kalmanf/kalmanfilter.py:649: RuntimeWarning: divide by zero encountered in true_divide
  R_mat, T_mat)


SVD did not converge
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
SVD did not converge


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/tsatools.py:612: RuntimeWarning: divide by zero encountered in true_divide
  invarcoefs = -np.log((1-params)/(1+params))


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial 

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


SVD did not converge
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are 

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


SVD did not converge
SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass y

The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are no

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
SVD did not converge


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are 

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
SVD did not converge
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.


/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are 

/home/cartest/anaconda3/lib/python3.6/site-packages/statsmodels/base/model.py:496: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial MA coefficients are not invertible
You should induce invertibility, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.
The computed initial AR coefficients are n

In [ ]:
predictions =  [[]] * len(test_year_dfs)
i = 0;


for ts in test_year_dfs:
    
    if len(ts.values) == 0:
        continue
    history = [x for x in ts]
    prediction = list()
    print(len(ts))
    for t in range(len(ts.index.values)):
        output = train_year_results[i].predict(t,t, typ ="linear")
        yhat = output[0]
        prediction.append(yhat)
        obs = ts.loc[t]
        history.append(obs)
        print('predicted=%f, expected=%f' % (yhat, obs))
        error = mean_squared_error(ts, prediction)
        print('Test MSE: %.3f' % error)
        
    if i ==0:
        plt.plot(ts)
        plt.plot(prediction, color='red')
        plt.show()
        i = i + 1
        
    predictions.append(prediction)
    